---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.3
        name: hackmd
        args:
          - mysqld
          - --character-set-server=utf8
          - --collation-server=utf8_general_ci
        env:
          - name: MYSQL_USER
            value: hackmd
          - name: MYSQL_PASSWORD
            value: hackmdpass
          - name: MYSQL_DATABASE
            value: hackmd
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "true"
        volumeMounts:
          - name: mariadb-data
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: rook-ceph-block
      resources:
        requests:
          storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: mariadb
  selector:
    app: mariadb
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hackmd
  name: hackmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackmd
  template:
    metadata:
      labels:
        app: hackmd
    spec:
      containers:
      - image: zakihmkc/growi-hackmd
        name: hackmd
        env:
          - name: CMD_DB_URL
            value: mysql://hackmd:hackmdpass@mariadb:3306/hackmd
          - name: CMD_CSP_ENABLE
            value: "false"
          - name: GROWI_URI
            value: http://192.168.0.185:3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hackmd
  name: hackmd
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: hackmd
  selector:
    app: hackmd
  type: LoadBalancer
